### PR TITLE
Basic Code Cleanup

### PR DESCRIPTION
**Pull request by ohoshk**
This logger could be much, MUCH more efficient with a simple code cleanup. Consider enacting the changes I'm proposing here for a nice cleanup and more efficient logger.

### CODE REVIEW

**Comment by catastrofi9** [comment]
....

**Comment by NotSwaraj** [comment]
You just deleting everything Mr Negro

**Comment by Zsirnight** [comment]
......................................................................

**Comment by qertyuiop12345678** [comment]
bruh moment

**Pull request closed without merging**
